SELECT DISTINCT CITY
FROM STATION
WHERE SUBSTRING(CITY, -1, 1) <> 'A'
AND SUBSTRING(CITY, -1, 1) <> 'E'
AND SUBSTRING(CITY, -1, 1) <> 'I'
AND SUBSTRING(CITY, -1, 1) <> 'O'
AND SUBSTRING(CITY, -1, 1) <> 'U';